### ISSUE TITLE
Published spec out of date

### ISSUE THREAD

**Issue by Ms2ger** [w3c/proximity#41]
https://w3c.github.io/proximity/ doesn't contain the changes from #39.

**Comment by anssiko** [comment]
https://w3c.github.io/proximity/ is being built from the `gh-pages` branch that has #39, so that seems to be a GitHub Pages issue. https://w3c.github.io/proximity/ should be identical to https://cdn.statically.io/gh/w3c/proximity/gh-pages/index.html but now the former is one commit behind.

@xfq can you investigate what's up with GitHub Pages?

**Comment by xfq** [comment]
@anssiko I'm not sure what caused this, so contacted GitHub Support on Aug 25, but haven't got reply from them yet.

**Comment by xfq** [comment]
It seems that the generated HTML has been updated. Closing this issue.
